version: '3.7'
services:
  db:
    image: postgres:12.3
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - backend
  web:
    build: .
    ports:
      - "80:3000"
      # - "3000:3000"
    environment:
      RAILS_ENV: development
    env_file: .env
    depends_on:
      - db
    networks:
      - backend

volumes:
  data:
    driver: local

networks:
  backend: