name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services: 
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install Dependencies
        run: |
          sudo apt install -yqq libpq-dev
          gem install bundler
          
      - name: Install Gems
        run: |
          bundle install
          
      - name: Run Tests
        env:
          PG_DATABASE: postgres
          PG_HOST: localhost
          PG_USER: postgres
          PG_PASSWORD: postgres
          RAILS_ENV: test
        run: |
          bundle exec rake db:create
          bundle exec rake db:schema:load
          bundle exec rake
